# Generated by Django 4.2.3 on 2023-07-28 17:01

from django.db import migrations, models
import django.db.models.deletion
import window_sill.models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SillThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SillWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.RenameField(
            model_name='windowsill',
            old_name='sill_name',
            new_name='color_name',
        ),
        migrations.AddField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('dex', 'dex'), ('wiech', 'wiech'), ('kobax', 'kobax')], default='dex'),
        ),
        migrations.AddField(
            model_name='sillcategory',
            name='max_length',
            field=models.PositiveSmallIntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='sillcategory',
            name='max_width',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sillcategory',
            name='min_length',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sillcategory',
            name='min_width',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='image',
            field=models.ImageField(null=True, upload_to=window_sill.models.sill_image_file_path),
        ),
        migrations.AlterField(
            model_name='sillcategory',
            name='price_unit',
            field=models.CharField(choices=[('mb', 'mb'), ('m2', 'm2')], default='mb'),
        ),
        migrations.AddField(
            model_name='sillcategory',
            name='additional_options',
            field=models.ManyToManyField(to='window_sill.additionaloption'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='thickness_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='window_sill.sillthickness'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='width_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='window_sill.sillwidth'),
        ),
    ]
