# Generated by Django 4.2.3 on 2023-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0002_additionaloption_sillthickness_sillwidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('wiech', 'wiech'), ('kobax', 'kobax'), ('dex', 'dex')], default='dex'),
        ),
    ]
