# Generated by Django 4.2.3 on 2023-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0006_alter_sillcategory_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='price_unit',
            field=models.CharField(choices=[('mb', 'mb'), ('m2', 'm2')], default='mb'),
        ),
    ]
