# Generated by Django 4.2.3 on 2023-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0007_alter_sillcategory_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('kobax', 'kobax'), ('dex', 'dex'), ('wiech', 'wiech')], default='dex'),
        ),
        migrations.AlterField(
            model_name='sillcategory',
            name='price_unit',
            field=models.CharField(choices=[('m2', 'm2'), ('mb', 'mb')], default='mb'),
        ),
    ]
