# Generated by Django 4.2.3 on 2023-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0008_alter_sillcategory_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('dex', 'dex'), ('wiech', 'wiech'), ('kobax', 'kobax')], default='dex'),
        ),
    ]
