# Generated by Django 4.2.3 on 2023-08-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0009_alter_sillcategory_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsill',
            name='sill_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='window_sill.sillcategory'),
        ),
        migrations.RemoveField(
            model_name='windowsill',
            name='thickness_option',
        ),
        migrations.RemoveField(
            model_name='windowsill',
            name='width_option',
        ),
        migrations.AddField(
            model_name='windowsill',
            name='thickness_option',
            field=models.ManyToManyField(to='window_sill.sillthickness'),
        ),
        migrations.AddField(
            model_name='windowsill',
            name='width_option',
            field=models.ManyToManyField(to='window_sill.sillwidth'),
        ),
    ]
