# Generated by Django 4.2.3 on 2023-08-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0011_remove_windowsill_price_sillthickness_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('dex', 'dex'), ('wiech', 'wiech'), ('kobax', 'kobax')], default='dex'),
        ),
    ]
