# Generated by Django 4.2.3 on 2023-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0012_alter_sillcategory_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('wiech', 'wiech'), ('kobax', 'kobax'), ('dex', 'dex')], default='dex'),
        ),
        migrations.AlterField(
            model_name='sillcategory',
            name='price_unit',
            field=models.CharField(choices=[('m2', 'm2'), ('mb', 'mb')], default='mb'),
        ),
    ]
