# Generated by Django 4.2.3 on 2023-08-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0013_alter_sillcategory_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('kobax', 'kobax'), ('dex', 'dex'), ('wiech', 'wiech')], default='dex'),
        ),
    ]
