# Generated by Django 4.2.3 on 2023-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0015_alter_sillcategory_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('dex', 'dex'), ('kobax', 'kobax'), ('wiech', 'wiech')], default='dex'),
        ),
        migrations.AlterField(
            model_name='sillcategory',
            name='price_unit',
            field=models.CharField(choices=[('mb', 'mb'), ('m2', 'm2')], default='mb'),
        ),
    ]
