# Generated by Django 4.2.3 on 2023-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0018_alter_sillcategory_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillcategory',
            name='manufacturer',
            field=models.CharField(choices=[('dex', 'dex'), ('wiech', 'wiech'), ('kobax', 'kobax')], default='dex'),
        ),
        migrations.AlterField(
            model_name='sillcategory',
            name='price_unit',
            field=models.CharField(choices=[('mb', 'mb'), ('m2', 'm2')], default='mb'),
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='thickness_option',
            field=models.ManyToManyField(blank=True, to='window_sill.sillthickness'),
        ),
        migrations.AlterField(
            model_name='windowsill',
            name='width_option',
            field=models.ManyToManyField(blank=True, to='window_sill.sillwidth'),
        ),
    ]
