# Generated by Django 4.2.4 on 2023-10-26 18:13

from django.db import migrations, models
import window_sill.models


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0020_alter_sillcategory_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowsill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=window_sill.models.sill_image_file_path),
        ),
    ]
