# Generated by Django 4.2.4 on 2023-10-26 18:13

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='technical_draw',
            field=models.ImageField(blank=True, null=True, upload_to=order.models.technical_image_file_path),
        ),
    ]
