# Generated by Django 4.2.4 on 2023-10-26 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('window_sill', '0021_alter_windowsill_image'),
        ('order', '0003_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='window_sill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='window_sill.windowsill'),
        ),
    ]
