# Generated by Django 4.2.4 on 2023-11-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('window_sill', '0021_alter_windowsill_image'),
        ('order', '0004_alter_order_user_alter_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='window_sill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='window_sill.windowsill'),
        ),
    ]
